name: Lint Specs

on:
  pull_request:
    paths:
      - "specs/**"

jobs:
  lint-specs:
    runs-on: ubuntu-latest
    name: check lint specs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: lint specs md
        run: just lint-specs-md-check
      - name: lint specs toc
        run: just lint-specs-toc-check
